name: Chain Kotlin SQK CI/CD

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    continue-on-error: false

    env:
      VERSION: build
      OSSRHUSERNAME: ossrhusername
      OSSRHPASSWORD: ossrhpassword

    steps:

      - name: Prepare system
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Java SDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: |
          envsubst '${env.VERSION}','${env.OSSRHUSERNAME}','${env.OSSRHPASSWORD}' < build.gradle > build.gradle.new
          mv build.gradle.new build.gradle
          ./gradlew assemble

      - name: Save executables
        uses: actions/upload-artifact@v2
        with:
          name: assembles_${{ github.sha }}
          path: build/libs/*.jar


  deploy:
    name: Deploy SDK
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: [build]

    env:
      OSSRHUSERNAME: ${secrets.OSSRH_LOGIN}
      OSSRHPASSWORD: ${secrets.OSSRH_PASS}

    steps:

      - name: Prepare system
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: assembles_${{ github.sha }}
          path: build/libs

      - name: Deploy SDK
        run: |
          VERSION=$(echo ${{ github.ref }} | sed "s/v//")
          export VERSION=$VERSION
          envsubst '${VERSION}','${env.OSSRHUSERNAME}','${env.OSSRHPASSWORD}' < build.gradle > build.gradle.new
          mv build.gradle.new build.gradle
          mkdir .gradle
          echo "${{ secrets.GPG_KEY_PRIVATE }}" > private.key
          gpg --import private.key
          gpg --export-secret-keys -o secring.gpg
          echo $GRADLE_USER_HOME
          echo "${{ secrets.GRADLE_PROPERTIES }}" | sudo tee $GRADLE_USER_HOME/gradle.properties
          ./gradlew -Psign uploadArchives
          ./gradlew closeAndReleaseRepository

